title: NA SWF Monitoring
#logo: /assests/img/Virginia Tech SuperDARN Solar Flare.png
lang: en-US
description: North America SWF Monitoring & X-RAP Modeling
plugins:
  - jekyll-remote-theme
remote_theme: benbalter/retlab

# Pages to include in header navigation
nav_pages:
  - flarecal.html
  - newdrap.html
  - flarelist.html
